version: '3.3'
services:
  scraper-api:
    image: spthk/amazon-product-scraper:0.0.1
    environment:
      - SCRAPER_HOST_PORT=8080
      - MYSQL_HOST=docker.for.mac.localhost
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_USER=root
      - MYSQL_DATABASE=test
