version: '3.3'
services:
  scraper-api:
    image: skp123/scraper:1.0
    environment:
      - DATA_STORE_URL= http://127.0.0.1:8081
    ports:
      - "8080:8080"
    depends_on:
      - db
      - datastore-api
  datastore-api:
    image: skp123/scrapestore:0.1
    environment:
      - DB_URL= http://127.0.0.1
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_USER=root
      - MYSQL_DATABASE=test
